spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/navada?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: navada
    password: hidn99

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
