spring:
  datasource:
    url: jdbc:log4jdbc:mysql://3.37.170.121:3306/navada?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: hidn
    password: hidn!99

  jpa:
    hibernate:
      ddl-auto: create
      show-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: i18n/exception
    encoding: UTF-8